name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make Scripts Executable
      run: chmod a+x docker/docker-setup.sh && chmod a+x docker/docker-build.sh
    - name: Enable Multi-Architecture Support in Docker
      run: ./docker/docker-setup.sh
    - name: Build the Docker image
      run: ./docker/docker-build.sh
