name: Print Working Directory

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual trigger

jobs:
  print-cwd:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Print the current working directory
      - name: Show current working directory
        run: |
          pwd
          ls -l
